//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ActionReadMore {
            get {
                return ResourceManager.GetString("ActionReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string applyoldagefrm {
            get {
                return ResourceManager.GetString("applyoldagefrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string btnclick {
            get {
                return ResourceManager.GetString("btnclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CmConTent {
            get {
                return ResourceManager.GetString("CmConTent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CMHeading {
            get {
                return ResourceManager.GetString("CMHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConAdd {
            get {
                return ResourceManager.GetString("ConAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConAddDetails {
            get {
                return ResourceManager.GetString("ConAddDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConEmail {
            get {
                return ResourceManager.GetString("ConEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConFax {
            get {
                return ResourceManager.GetString("ConFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConPhone {
            get {
                return ResourceManager.GetString("ConPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Deptname {
            get {
                return ResourceManager.GetString("Deptname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FCopyright {
            get {
                return ResourceManager.GetString("FCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeadAadhar {
            get {
                return ResourceManager.GetString("HeadAadhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeadBenList {
            get {
                return ResourceManager.GetString("HeadBenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeadBenStatus {
            get {
                return ResourceManager.GetString("HeadBenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeadBenStatuslist {
            get {
                return ResourceManager.GetString("HeadBenStatuslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeadChkPayment {
            get {
                return ResourceManager.GetString("HeadChkPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HeadPFMS {
            get {
                return ResourceManager.GetString("HeadPFMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Homeabt {
            get {
                return ResourceManager.GetString("Homeabt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomeabtDetail {
            get {
                return ResourceManager.GetString("HomeabtDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomeabtDetailDis {
            get {
                return ResourceManager.GetString("HomeabtDetailDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpLinkAcc {
            get {
                return ResourceManager.GetString("ImpLinkAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpLinkCentral {
            get {
                return ResourceManager.GetString("ImpLinkCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpLinkEleave {
            get {
                return ResourceManager.GetString("ImpLinkEleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpLinkGov {
            get {
                return ResourceManager.GetString("ImpLinkGov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpLinkPro {
            get {
                return ResourceManager.GetString("ImpLinkPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpLinkRoad {
            get {
                return ResourceManager.GetString("ImpLinkRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpLinkUrban {
            get {
                return ResourceManager.GetString("ImpLinkUrban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LockBen {
            get {
                return ResourceManager.GetString("LockBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LogoDis {
            get {
                return ResourceManager.GetString("LogoDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LogoEdu {
            get {
                return ResourceManager.GetString("LogoEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LstofOldAge {
            get {
                return ResourceManager.GetString("LstofOldAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD1 {
            get {
                return ResourceManager.GetString("MD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD1FY {
            get {
                return ResourceManager.GetString("MD1FY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD1TY {
            get {
                return ResourceManager.GetString("MD1TY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD2 {
            get {
                return ResourceManager.GetString("MD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD2FY {
            get {
                return ResourceManager.GetString("MD2FY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD2TY {
            get {
                return ResourceManager.GetString("MD2TY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD3 {
            get {
                return ResourceManager.GetString("MD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD3FY {
            get {
                return ResourceManager.GetString("MD3FY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD3TY {
            get {
                return ResourceManager.GetString("MD3TY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD4 {
            get {
                return ResourceManager.GetString("MD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD4FY {
            get {
                return ResourceManager.GetString("MD4FY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD4TY {
            get {
                return ResourceManager.GetString("MD4TY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD5 {
            get {
                return ResourceManager.GetString("MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD5FY {
            get {
                return ResourceManager.GetString("MD5FY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD5TY {
            get {
                return ResourceManager.GetString("MD5TY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuAadhar {
            get {
                return ResourceManager.GetString("MenuAadhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuActsRules {
            get {
                return ResourceManager.GetString("MenuActsRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuAsha {
            get {
                return ResourceManager.GetString("MenuAsha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuAshaFacilitator {
            get {
                return ResourceManager.GetString("MenuAshaFacilitator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuAssetsDeclaration {
            get {
                return ResourceManager.GetString("MenuAssetsDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Menuassistivedevices {
            get {
                return ResourceManager.GetString("Menuassistivedevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuBenLst {
            get {
                return ResourceManager.GetString("MenuBenLst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuBoardMemberProfile {
            get {
                return ResourceManager.GetString("MenuBoardMemberProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuChairmanBOD {
            get {
                return ResourceManager.GetString("MenuChairmanBOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuCirculars {
            get {
                return ResourceManager.GetString("MenuCirculars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuComplaintEnquiry {
            get {
                return ResourceManager.GetString("MenuComplaintEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuContacts {
            get {
                return ResourceManager.GetString("MenuContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuContactUs {
            get {
                return ResourceManager.GetString("MenuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuCorrigendumInfo {
            get {
                return ResourceManager.GetString("MenuCorrigendumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuDebard {
            get {
                return ResourceManager.GetString("MenuDebard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuDepartmentLogin {
            get {
                return ResourceManager.GetString("MenuDepartmentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuDepartmentReview {
            get {
                return ResourceManager.GetString("MenuDepartmentReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuDevlopmentCommissioner {
            get {
                return ResourceManager.GetString("MenuDevlopmentCommissioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuDistCordContact {
            get {
                return ResourceManager.GetString("MenuDistCordContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuDocuments {
            get {
                return ResourceManager.GetString("MenuDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenueBookGallery {
            get {
                return ResourceManager.GetString("MenueBookGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuEntryReport {
            get {
                return ResourceManager.GetString("MenuEntryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuFeedback {
            get {
                return ResourceManager.GetString("MenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuHelpdesk {
            get {
                return ResourceManager.GetString("MenuHelpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuHindi {
            get {
                return ResourceManager.GetString("MenuHindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuHistory {
            get {
                return ResourceManager.GetString("MenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuImportantNotice {
            get {
                return ResourceManager.GetString("MenuImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuISO {
            get {
                return ResourceManager.GetString("MenuISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuISOdis {
            get {
                return ResourceManager.GetString("MenuISOdis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Menukeycontact {
            get {
                return ResourceManager.GetString("Menukeycontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuListMD {
            get {
                return ResourceManager.GetString("MenuListMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Menulistofsuppliers {
            get {
                return ResourceManager.GetString("Menulistofsuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuLotteryReport {
            get {
                return ResourceManager.GetString("MenuLotteryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuMDBSBCCL {
            get {
                return ResourceManager.GetString("MenuMDBSBCCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuMediaNews {
            get {
                return ResourceManager.GetString("MenuMediaNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuMessage {
            get {
                return ResourceManager.GetString("MenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuMinister {
            get {
                return ResourceManager.GetString("MenuMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuMobileApp {
            get {
                return ResourceManager.GetString("MenuMobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuNotes {
            get {
                return ResourceManager.GetString("MenuNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuNotice {
            get {
                return ResourceManager.GetString("MenuNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuNotification {
            get {
                return ResourceManager.GetString("MenuNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuObjective {
            get {
                return ResourceManager.GetString("MenuObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuOfficeOrder {
            get {
                return ResourceManager.GetString("MenuOfficeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuOfficerDetails {
            get {
                return ResourceManager.GetString("MenuOfficerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuOfficerProfile {
            get {
                return ResourceManager.GetString("MenuOfficerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuOnlineUser {
            get {
                return ResourceManager.GetString("MenuOnlineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Menuorg {
            get {
                return ResourceManager.GetString("Menuorg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuOthers {
            get {
                return ResourceManager.GetString("MenuOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuOverview {
            get {
                return ResourceManager.GetString("MenuOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuPaymentRpt {
            get {
                return ResourceManager.GetString("MenuPaymentRpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuPhotoGallery {
            get {
                return ResourceManager.GetString("MenuPhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuPIUReview {
            get {
                return ResourceManager.GetString("MenuPIUReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuPR1 {
            get {
                return ResourceManager.GetString("MenuPR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuPR2 {
            get {
                return ResourceManager.GetString("MenuPR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuPR3 {
            get {
                return ResourceManager.GetString("MenuPR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuProcedingReview {
            get {
                return ResourceManager.GetString("MenuProcedingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuProjectView {
            get {
                return ResourceManager.GetString("MenuProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRateNegotiation {
            get {
                return ResourceManager.GetString("MenuRateNegotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRequest {
            get {
                return ResourceManager.GetString("MenuRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRequestQuery {
            get {
                return ResourceManager.GetString("MenuRequestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRequestResponse {
            get {
                return ResourceManager.GetString("MenuRequestResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Menurevision {
            get {
                return ResourceManager.GetString("Menurevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRpt {
            get {
                return ResourceManager.GetString("MenuRpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptAshaActivity {
            get {
                return ResourceManager.GetString("MenuRptAshaActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptAshaActivityProgress {
            get {
                return ResourceManager.GetString("MenuRptAshaActivityProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptAshaActivityVerStatus {
            get {
                return ResourceManager.GetString("MenuRptAshaActivityVerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptAshaFacActivity {
            get {
                return ResourceManager.GetString("MenuRptAshaFacActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptAshaFacLogin {
            get {
                return ResourceManager.GetString("MenuRptAshaFacLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptAshaLogin {
            get {
                return ResourceManager.GetString("MenuRptAshaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptCard {
            get {
                return ResourceManager.GetString("MenuRptCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRptCons {
            get {
                return ResourceManager.GetString("MenuRptCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuRTI {
            get {
                return ResourceManager.GetString("MenuRTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuScreenReader {
            get {
                return ResourceManager.GetString("MenuScreenReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuSeceretaryBCD {
            get {
                return ResourceManager.GetString("MenuSeceretaryBCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuSentPFMS {
            get {
                return ResourceManager.GetString("MenuSentPFMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuSitemap {
            get {
                return ResourceManager.GetString("MenuSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuSkey {
            get {
                return ResourceManager.GetString("MenuSkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuSkip {
            get {
                return ResourceManager.GetString("MenuSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuTender {
            get {
                return ResourceManager.GetString("MenuTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuTenderDetails {
            get {
                return ResourceManager.GetString("MenuTenderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuTenderProcedding {
            get {
                return ResourceManager.GetString("MenuTenderProcedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuTextSize {
            get {
                return ResourceManager.GetString("MenuTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuTheme {
            get {
                return ResourceManager.GetString("MenuTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuTransferOrder {
            get {
                return ResourceManager.GetString("MenuTransferOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuTxtbook {
            get {
                return ResourceManager.GetString("MenuTxtbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn1 {
            get {
                return ResourceManager.GetString("MenuUn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn10 {
            get {
                return ResourceManager.GetString("MenuUn10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn11 {
            get {
                return ResourceManager.GetString("MenuUn11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn12 {
            get {
                return ResourceManager.GetString("MenuUn12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn13 {
            get {
                return ResourceManager.GetString("MenuUn13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn14 {
            get {
                return ResourceManager.GetString("MenuUn14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn15 {
            get {
                return ResourceManager.GetString("MenuUn15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn16 {
            get {
                return ResourceManager.GetString("MenuUn16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn17 {
            get {
                return ResourceManager.GetString("MenuUn17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn2 {
            get {
                return ResourceManager.GetString("MenuUn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn3 {
            get {
                return ResourceManager.GetString("MenuUn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn4 {
            get {
                return ResourceManager.GetString("MenuUn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn5 {
            get {
                return ResourceManager.GetString("MenuUn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn6 {
            get {
                return ResourceManager.GetString("MenuUn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn7 {
            get {
                return ResourceManager.GetString("MenuUn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn8 {
            get {
                return ResourceManager.GetString("MenuUn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn9 {
            get {
                return ResourceManager.GetString("MenuUn9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUn91 {
            get {
                return ResourceManager.GetString("MenuUn91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUndertaking {
            get {
                return ResourceManager.GetString("MenuUndertaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuUserManual {
            get {
                return ResourceManager.GetString("MenuUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenuVideoGallery {
            get {
                return ResourceManager.GetString("MenuVideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinsContent {
            get {
                return ResourceManager.GetString("MinsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinsHeading {
            get {
                return ResourceManager.GetString("MinsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth1 {
            get {
                return ResourceManager.GetString("Mnth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth10 {
            get {
                return ResourceManager.GetString("Mnth10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth11 {
            get {
                return ResourceManager.GetString("Mnth11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth12 {
            get {
                return ResourceManager.GetString("Mnth12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth2 {
            get {
                return ResourceManager.GetString("Mnth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth3 {
            get {
                return ResourceManager.GetString("Mnth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth4 {
            get {
                return ResourceManager.GetString("Mnth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth5 {
            get {
                return ResourceManager.GetString("Mnth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth6 {
            get {
                return ResourceManager.GetString("Mnth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth7 {
            get {
                return ResourceManager.GetString("Mnth7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth8 {
            get {
                return ResourceManager.GetString("Mnth8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mnth9 {
            get {
                return ResourceManager.GetString("Mnth9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuAdministration {
            get {
                return ResourceManager.GetString("MnuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuHEdu {
            get {
                return ResourceManager.GetString("MnuHEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuHigher {
            get {
                return ResourceManager.GetString("MnuHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuMassEdu {
            get {
                return ResourceManager.GetString("MnuMassEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuMidaymeal {
            get {
                return ResourceManager.GetString("MnuMidaymeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuPD {
            get {
                return ResourceManager.GetString("MnuPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuPEdu {
            get {
                return ResourceManager.GetString("MnuPEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuPrimary {
            get {
                return ResourceManager.GetString("MnuPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuRD {
            get {
                return ResourceManager.GetString("MnuRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuResearch {
            get {
                return ResourceManager.GetString("MnuResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuSecondary {
            get {
                return ResourceManager.GetString("MnuSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MnuSEdu {
            get {
                return ResourceManager.GetString("MnuSEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PaymentDone {
            get {
                return ResourceManager.GetString("PaymentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PFMSAccp {
            get {
                return ResourceManager.GetString("PFMSAccp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextArchive {
            get {
                return ResourceManager.GetString("TextArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextAssestFile {
            get {
                return ResourceManager.GetString("TextAssestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextDate {
            get {
                return ResourceManager.GetString("TextDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextDegi {
            get {
                return ResourceManager.GetString("TextDegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextDetail {
            get {
                return ResourceManager.GetString("TextDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextDocument {
            get {
                return ResourceManager.GetString("TextDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextFeature {
            get {
                return ResourceManager.GetString("TextFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextFeedbackContent {
            get {
                return ResourceManager.GetString("TextFeedbackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextFeedbackHeading {
            get {
                return ResourceManager.GetString("TextFeedbackHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextHeading {
            get {
                return ResourceManager.GetString("TextHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextImportant {
            get {
                return ResourceManager.GetString("TextImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextKey {
            get {
                return ResourceManager.GetString("TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Textlatest {
            get {
                return ResourceManager.GetString("Textlatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextLetterNo {
            get {
                return ResourceManager.GetString("TextLetterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextLink {
            get {
                return ResourceManager.GetString("TextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextMax {
            get {
                return ResourceManager.GetString("TextMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextMin {
            get {
                return ResourceManager.GetString("TextMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextNews {
            get {
                return ResourceManager.GetString("TextNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextPublishing {
            get {
                return ResourceManager.GetString("TextPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextResize {
            get {
                return ResourceManager.GetString("TextResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextSl {
            get {
                return ResourceManager.GetString("TextSl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextSubject {
            get {
                return ResourceManager.GetString("TextSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextTender {
            get {
                return ResourceManager.GetString("TextTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextUpdate {
            get {
                return ResourceManager.GetString("TextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TotlBenCount {
            get {
                return ResourceManager.GetString("TotlBenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtApply {
            get {
                return ResourceManager.GetString("TxtApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtasset {
            get {
                return ResourceManager.GetString("txtasset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtbalkbalika {
            get {
                return ResourceManager.GetString("txtbalkbalika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtBlk {
            get {
                return ResourceManager.GetString("txtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtboard {
            get {
                return ResourceManager.GetString("txtboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtbstpracts {
            get {
                return ResourceManager.GetString("txtbstpracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtcmfcell {
            get {
                return ResourceManager.GetString("txtcmfcell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtCommercial {
            get {
                return ResourceManager.GetString("txtCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtcomplaint {
            get {
                return ResourceManager.GetString("txtcomplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtConsultancy {
            get {
                return ResourceManager.GetString("TxtConsultancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Txtcrtificatelnk1 {
            get {
                return ResourceManager.GetString("Txtcrtificatelnk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Txtcrtificatelnk2 {
            get {
                return ResourceManager.GetString("Txtcrtificatelnk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtDDate {
            get {
                return ResourceManager.GetString("TxtDDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtDFDate {
            get {
                return ResourceManager.GetString("TxtDFDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtDirectorate {
            get {
                return ResourceManager.GetString("txtDirectorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtdiscrt {
            get {
                return ResourceManager.GetString("txtdiscrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtdisStatus {
            get {
                return ResourceManager.GetString("txtdisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtDist {
            get {
                return ResourceManager.GetString("txtDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtDur {
            get {
                return ResourceManager.GetString("TxtDur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtDwnForm {
            get {
                return ResourceManager.GetString("TxtDwnForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtDwonload {
            get {
                return ResourceManager.GetString("TxtDwonload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtEoffice {
            get {
                return ResourceManager.GetString("TxtEoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtEOI {
            get {
                return ResourceManager.GetString("TxtEOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtEOIF {
            get {
                return ResourceManager.GetString("TxtEOIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtEPC {
            get {
                return ResourceManager.GetString("TxtEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtFDate {
            get {
                return ResourceManager.GetString("TxtFDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtfinyear {
            get {
                return ResourceManager.GetString("txtfinyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtFireScheme {
            get {
                return ResourceManager.GetString("TxtFireScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtFree {
            get {
                return ResourceManager.GetString("txtFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtinfo {
            get {
                return ResourceManager.GetString("txtinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMENT OF EDUCATION DIRECTORY.
        /// </summary>
        internal static string txtkeycont {
            get {
                return ResourceManager.GetString("txtkeycont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtLetterDt {
            get {
                return ResourceManager.GetString("txtLetterDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtLetterType {
            get {
                return ResourceManager.GetString("txtLetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtmedaha {
            get {
                return ResourceManager.GetString("txtmedaha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtNContractor {
            get {
                return ResourceManager.GetString("TxtNContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtnewclip {
            get {
                return ResourceManager.GetString("txtnewclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtngoreg {
            get {
                return ResourceManager.GetString("txtngoreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtNic {
            get {
                return ResourceManager.GetString("TxtNic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtnotice {
            get {
                return ResourceManager.GetString("txtnotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtOldAge {
            get {
                return ResourceManager.GetString("TxtOldAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtonliecomplaint {
            get {
                return ResourceManager.GetString("txtonliecomplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtOnlineApply {
            get {
                return ResourceManager.GetString("TxtOnlineApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtpan {
            get {
                return ResourceManager.GetString("txtpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtpay {
            get {
                return ResourceManager.GetString("txtpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtPMIS {
            get {
                return ResourceManager.GetString("TxtPMIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtPrimaryEducation {
            get {
                return ResourceManager.GetString("txtPrimaryEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtquickDonate {
            get {
                return ResourceManager.GetString("txtquickDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtregngo {
            get {
                return ResourceManager.GetString("txtregngo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtregwith {
            get {
                return ResourceManager.GetString("txtregwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtregwithlink1 {
            get {
                return ResourceManager.GetString("txtregwithlink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtregwithlink2 {
            get {
                return ResourceManager.GetString("txtregwithlink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtReliefFund {
            get {
                return ResourceManager.GetString("txtReliefFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtRFP {
            get {
                return ResourceManager.GetString("txtRFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtRFPF {
            get {
                return ResourceManager.GetString("txtRFPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScan1 {
            get {
                return ResourceManager.GetString("txtScan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScan2 {
            get {
                return ResourceManager.GetString("txtScan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtschm {
            get {
                return ResourceManager.GetString("txtschm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenBold {
            get {
                return ResourceManager.GetString("txtScreenBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenGo {
            get {
                return ResourceManager.GetString("txtScreenGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenhal {
            get {
                return ResourceManager.GetString("txtScreenhal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenJAWS {
            get {
                return ResourceManager.GetString("txtScreenJAWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenNova {
            get {
                return ResourceManager.GetString("txtScreenNova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenNVDA {
            get {
                return ResourceManager.GetString("txtScreenNVDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenSAFA {
            get {
                return ResourceManager.GetString("txtScreenSAFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenText {
            get {
                return ResourceManager.GetString("txtScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenthu {
            get {
                return ResourceManager.GetString("txtScreenthu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenweb {
            get {
                return ResourceManager.GetString("txtScreenweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtScreenwindows {
            get {
                return ResourceManager.GetString("txtScreenwindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtShortText {
            get {
                return ResourceManager.GetString("TxtShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtShortTextBold {
            get {
                return ResourceManager.GetString("txtShortTextBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtsignlan {
            get {
                return ResourceManager.GetString("txtsignlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtsignlanvideo {
            get {
                return ResourceManager.GetString("txtsignlanvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtSNo {
            get {
                return ResourceManager.GetString("TxtSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtStatusRpt {
            get {
                return ResourceManager.GetString("txtStatusRpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtStauts {
            get {
                return ResourceManager.GetString("txtStauts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtstdcrd {
            get {
                return ResourceManager.GetString("txtstdcrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtstory {
            get {
                return ResourceManager.GetString("txtstory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtsuccess {
            get {
                return ResourceManager.GetString("txtsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtTDate {
            get {
                return ResourceManager.GetString("txtTDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtTEMIS {
            get {
                return ResourceManager.GetString("txtTEMIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtTender {
            get {
                return ResourceManager.GetString("TxtTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txttndr {
            get {
                return ResourceManager.GetString("txttndr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtusfull {
            get {
                return ResourceManager.GetString("txtusfull", resourceCulture);
            }
        }
    }
}
