//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Bhusamadhan.UploadImageService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImageWebServiceSoap", Namespace="http://10.133.25.21/")]
    public partial class ImageWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDOCOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPDF1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewMergeDocOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ImageWebService() {
            this.Url = global::Bhusamadhan.Properties.Settings.Default.Bhusamadhan_UploadImageService_ImageWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertImageCompletedEventHandler InsertImageCompleted;
        
        /// <remarks/>
        public event InsertDocCompletedEventHandler InsertDocCompleted;
        
        /// <remarks/>
        public event DeleteDOCCompletedEventHandler DeleteDOCCompleted;
        
        /// <remarks/>
        public event InsertPDFCompletedEventHandler InsertPDFCompleted;
        
        /// <remarks/>
        public event InsertPDF1CompletedEventHandler InsertPDF1Completed;
        
        /// <remarks/>
        public event ViewDocCompletedEventHandler ViewDocCompleted;
        
        /// <remarks/>
        public event ViewMergeDocCompletedEventHandler ViewMergeDocCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.133.25.21/InsertImage", RequestNamespace="http://10.133.25.21/", ResponseNamespace="http://10.133.25.21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertImage(string _path, string _Photo, string _filename) {
            object[] results = this.Invoke("InsertImage", new object[] {
                        _path,
                        _Photo,
                        _filename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertImageAsync(string _path, string _Photo, string _filename) {
            this.InsertImageAsync(_path, _Photo, _filename, null);
        }
        
        /// <remarks/>
        public void InsertImageAsync(string _path, string _Photo, string _filename, object userState) {
            if ((this.InsertImageOperationCompleted == null)) {
                this.InsertImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertImageOperationCompleted);
            }
            this.InvokeAsync("InsertImage", new object[] {
                        _path,
                        _Photo,
                        _filename}, this.InsertImageOperationCompleted, userState);
        }
        
        private void OnInsertImageOperationCompleted(object arg) {
            if ((this.InsertImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertImageCompleted(this, new InsertImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.133.25.21/InsertDoc", RequestNamespace="http://10.133.25.21/", ResponseNamespace="http://10.133.25.21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertDoc(string _Doc, string _Docpath, string _filename, string _FileExt) {
            object[] results = this.Invoke("InsertDoc", new object[] {
                        _Doc,
                        _Docpath,
                        _filename,
                        _FileExt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertDocAsync(string _Doc, string _Docpath, string _filename, string _FileExt) {
            this.InsertDocAsync(_Doc, _Docpath, _filename, _FileExt, null);
        }
        
        /// <remarks/>
        public void InsertDocAsync(string _Doc, string _Docpath, string _filename, string _FileExt, object userState) {
            if ((this.InsertDocOperationCompleted == null)) {
                this.InsertDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDocOperationCompleted);
            }
            this.InvokeAsync("InsertDoc", new object[] {
                        _Doc,
                        _Docpath,
                        _filename,
                        _FileExt}, this.InsertDocOperationCompleted, userState);
        }
        
        private void OnInsertDocOperationCompleted(object arg) {
            if ((this.InsertDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertDocCompleted(this, new InsertDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.133.25.21/DeleteDOC", RequestNamespace="http://10.133.25.21/", ResponseNamespace="http://10.133.25.21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteDOC(string _path) {
            object[] results = this.Invoke("DeleteDOC", new object[] {
                        _path});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDOCAsync(string _path) {
            this.DeleteDOCAsync(_path, null);
        }
        
        /// <remarks/>
        public void DeleteDOCAsync(string _path, object userState) {
            if ((this.DeleteDOCOperationCompleted == null)) {
                this.DeleteDOCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDOCOperationCompleted);
            }
            this.InvokeAsync("DeleteDOC", new object[] {
                        _path}, this.DeleteDOCOperationCompleted, userState);
        }
        
        private void OnDeleteDOCOperationCompleted(object arg) {
            if ((this.DeleteDOCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDOCCompleted(this, new DeleteDOCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.133.25.21/InsertPDF", RequestNamespace="http://10.133.25.21/", ResponseNamespace="http://10.133.25.21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertPDF(string _path, string _Photo, string _filename, string _fileExt) {
            object[] results = this.Invoke("InsertPDF", new object[] {
                        _path,
                        _Photo,
                        _filename,
                        _fileExt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPDFAsync(string _path, string _Photo, string _filename, string _fileExt) {
            this.InsertPDFAsync(_path, _Photo, _filename, _fileExt, null);
        }
        
        /// <remarks/>
        public void InsertPDFAsync(string _path, string _Photo, string _filename, string _fileExt, object userState) {
            if ((this.InsertPDFOperationCompleted == null)) {
                this.InsertPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPDFOperationCompleted);
            }
            this.InvokeAsync("InsertPDF", new object[] {
                        _path,
                        _Photo,
                        _filename,
                        _fileExt}, this.InsertPDFOperationCompleted, userState);
        }
        
        private void OnInsertPDFOperationCompleted(object arg) {
            if ((this.InsertPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPDFCompleted(this, new InsertPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.133.25.21/InsertPDF1", RequestNamespace="http://10.133.25.21/", ResponseNamespace="http://10.133.25.21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertPDF1(string _path, string _Photo, string _filename) {
            object[] results = this.Invoke("InsertPDF1", new object[] {
                        _path,
                        _Photo,
                        _filename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPDF1Async(string _path, string _Photo, string _filename) {
            this.InsertPDF1Async(_path, _Photo, _filename, null);
        }
        
        /// <remarks/>
        public void InsertPDF1Async(string _path, string _Photo, string _filename, object userState) {
            if ((this.InsertPDF1OperationCompleted == null)) {
                this.InsertPDF1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPDF1OperationCompleted);
            }
            this.InvokeAsync("InsertPDF1", new object[] {
                        _path,
                        _Photo,
                        _filename}, this.InsertPDF1OperationCompleted, userState);
        }
        
        private void OnInsertPDF1OperationCompleted(object arg) {
            if ((this.InsertPDF1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPDF1Completed(this, new InsertPDF1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.133.25.21/ViewDoc", RequestNamespace="http://10.133.25.21/", ResponseNamespace="http://10.133.25.21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnValue[] ViewDoc(string skey, string _path, string _Cap, string _Type) {
            object[] results = this.Invoke("ViewDoc", new object[] {
                        skey,
                        _path,
                        _Cap,
                        _Type});
            return ((ReturnValue[])(results[0]));
        }
        
        /// <remarks/>
        public void ViewDocAsync(string skey, string _path, string _Cap, string _Type) {
            this.ViewDocAsync(skey, _path, _Cap, _Type, null);
        }
        
        /// <remarks/>
        public void ViewDocAsync(string skey, string _path, string _Cap, string _Type, object userState) {
            if ((this.ViewDocOperationCompleted == null)) {
                this.ViewDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewDocOperationCompleted);
            }
            this.InvokeAsync("ViewDoc", new object[] {
                        skey,
                        _path,
                        _Cap,
                        _Type}, this.ViewDocOperationCompleted, userState);
        }
        
        private void OnViewDocOperationCompleted(object arg) {
            if ((this.ViewDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewDocCompleted(this, new ViewDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.133.25.21/ViewMergeDoc", RequestNamespace="http://10.133.25.21/", ResponseNamespace="http://10.133.25.21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnValue[] ViewMergeDoc(string skey, string Filepath, string _Cap) {
            object[] results = this.Invoke("ViewMergeDoc", new object[] {
                        skey,
                        Filepath,
                        _Cap});
            return ((ReturnValue[])(results[0]));
        }
        
        /// <remarks/>
        public void ViewMergeDocAsync(string skey, string Filepath, string _Cap) {
            this.ViewMergeDocAsync(skey, Filepath, _Cap, null);
        }
        
        /// <remarks/>
        public void ViewMergeDocAsync(string skey, string Filepath, string _Cap, object userState) {
            if ((this.ViewMergeDocOperationCompleted == null)) {
                this.ViewMergeDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewMergeDocOperationCompleted);
            }
            this.InvokeAsync("ViewMergeDoc", new object[] {
                        skey,
                        Filepath,
                        _Cap}, this.ViewMergeDocOperationCompleted, userState);
        }
        
        private void OnViewMergeDocOperationCompleted(object arg) {
            if ((this.ViewMergeDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewMergeDocCompleted(this, new ViewMergeDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.133.25.21/")]
    public partial class ReturnValue {
        
        private string skeyField;
        
        private string sValueField;
        
        private string capField;
        
        /// <remarks/>
        public string Skey {
            get {
                return this.skeyField;
            }
            set {
                this.skeyField = value;
            }
        }
        
        /// <remarks/>
        public string SValue {
            get {
                return this.sValueField;
            }
            set {
                this.sValueField = value;
            }
        }
        
        /// <remarks/>
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InsertImageCompletedEventHandler(object sender, InsertImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InsertDocCompletedEventHandler(object sender, InsertDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DeleteDOCCompletedEventHandler(object sender, DeleteDOCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDOCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDOCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InsertPDFCompletedEventHandler(object sender, InsertPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InsertPDF1CompletedEventHandler(object sender, InsertPDF1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPDF1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPDF1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ViewDocCompletedEventHandler(object sender, ViewDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ViewMergeDocCompletedEventHandler(object sender, ViewMergeDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewMergeDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewMergeDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnValue[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591